insert into app_upgrade (upgrade) values ('upgrade-00003.sql');

insert into intl_key (name) values ('btn-copy')
                                 , ('ln-system')
				 , ('str-username/user_name')
				 , ('lbl-person')
;

insert into intl (key                     , lang, val)
          values ('btn-copy'              , 'en', 'Copy')
	       , ('btn-copy'              , 'es', 'Copiar')
	       , ('ln-system'             , 'en', 'System')
	       , ('ln-system'             , 'es', 'Sistema')
	       , ('str-username/user_name', 'en', 'Username: %user_name')
	       , ('str-username/user_name', 'es', 'Usuario: %user_name')
	       , ('lbl-person', 'es', 'Person: ')
	       , ('lbl-person', 'en', 'Persona: ')
;

alter table item_option
drop  constraint item_option_id_item_fkey,
  add constraint item_option_id_item_fkey
      foreign key (id_item)
      references item(id)
      on delete cascade;

update intl set val = val || '&nbsp;' where key like 'lbl-%';


insert into intl_key (name)
values ('dta-business-name')
     , ('dta-profit-business-share')
     , ('dta-profit-services-share')
     , ('dta-profit-partners-share')
     , ('dta-partner-count')
     , ('dta-card-multiplicative')
     , ('dta-business-address')
     , ('dta-business-state')
     , ('dta-business-post-code')
     , ('dta-business-telephone')
     , ('dta-business-website')
     , ('dta-default-font')
     , ('dta-default-language')
;

insert into intl (key, lang, val)
values ('dta-business-name'        , 'en', 'Business Name')
     , ('dta-profit-business-share', 'en', 'Business Profit Share')
     , ('dta-profit-services-share', 'en', 'Services Profit Share')
     , ('dta-profit-partners-share', 'en', 'Partners Profit Share')
     , ('dta-partner-count'        , 'en', 'Partner Number')
     , ('dta-card-multiplicative'  , 'en', 'Card Payment Multiplicative')
     , ('dta-business-address'     , 'en', 'Business Address')
     , ('dta-business-state'       , 'en', 'Business State')
     , ('dta-business-post-code'   , 'en', 'Business Post Code')
     , ('dta-business-telephone'   , 'en', 'Business Phone Number')
     , ('dta-business-website'     , 'en', 'Business Website')
     , ('dta-default-font'         , 'en', 'Display Font')
     , ('dta-default-language'     , 'en', 'System Language')
     , ('dta-business-name'        , 'es', 'Nombre del Negocio')
     , ('dta-profit-business-share', 'es', 'Parte de las Ganancias del Negocio')
     , ('dta-profit-services-share', 'es', 'Parte de las Ganancias de los Servicios')
     , ('dta-profit-partners-share', 'es', 'Parte de las Ganancias de los Socios')
     , ('dta-partner-count'        , 'es', 'Número de Socios')
     , ('dta-card-multiplicative'  , 'es', 'Multiplicativo de Pago con Tarjeta')
     , ('dta-business-address'     , 'es', 'Dirección del Negocio')
     , ('dta-business-state'       , 'es', 'Estado del Negocio')
     , ('dta-business-post-code'   , 'es', 'Código Postal del Negocio')
     , ('dta-business-telephone'   , 'es', 'Número de Teléfono del Negocio')
     , ('dta-business-website'     , 'es', 'Sitio Web del Negocio')
     , ('dta-default-font'         , 'es', 'Tipo de Letra')
     , ('dta-default-language'     , 'es', 'Lenguaje del Sistema')
;

insert into intl_key (name)
values ('prm-add-expense')
     , ('prm-add-new-item')
     , ('prm-add-new-menu-group')
     , ('prm-add-option-to-item')
     , ('prm-add-services-expense')
     , ('prm-add-user')
     , ('prm-add-user-roles')
     , ('prm-assign-bill-item-to-person')
     , ('prm-assign-role-permissions')
     , ('prm-assign-user-roles')
     , ('prm-can-translate')
     , ('prm-change-app-values')
     , ('prm-change-bill-item')
     , ('prm-change-bill-item-price')
     , ('prm-change-bill-location')
     , ('prm-change-other-users-language')
     , ('prm-change-other-users-name')
     , ('prm-change-other-users-password')
     , ('prm-change-stock-status')
     , ('prm-change-user-enabled')
     , ('prm-charge-bill')
     , ('prm-close-accounts')
     , ('prm-create-bill-item')
     , ('prm-create-new-bill')
     , ('prm-create-new-option')
     , ('prm-create-new-option-group')
     , ('prm-delete-bill-item')
     , ('prm-delete-item')
     , ('prm-delete-roles')
     , ('prm-delete-user')
     , ('prm-list-bills')
     , ('prm-list-closed-accounts')
     , ('prm-list-closed-bills')
     , ('prm-list-closed-services')
     , ('prm-list-items')
     , ('prm-list-roles')
     , ('prm-list-services')
     , ('prm-list-users')
     , ('prm-print-bill')
     , ('prm-remove-option-from-item')
     , ('prm-set-item-charge')
     , ('prm-set-item-menu-group')
     , ('prm-set-item-name')
     , ('prm-set-option-charge')
     , ('prm-set-option-group')
     , ('prm-set-option-in-stock')
     , ('prm-set-option-name')
     , ('prm-set-options-to-bill-item')
     , ('prm-view-accounts')
     , ('prm-view-app-values')
     , ('prm-view-closed-account')
     , ('prm-view-closed-bill')
     , ('prm-view-closed-services')
     , ('prm-view-item')
     , ('prm-view-log')
     , ('prm-view-open-bill')
     , ('prm-view-option')
     , ('prm-view-other-users')
     , ('prm-view-role')
;

insert into intl (val, lang, key)
values ('Añadir Gasto'                                  , 'es', 'prm-add-expense')
     , ('Add Expense'                                   , 'en', 'prm-add-expense')
     , ('Añadir Producto'                               , 'es', 'prm-add-new-item')
     , ('Add Item'                                      , 'en', 'prm-add-new-item')
     , ('Añadir Grupo de Menú'                          , 'es', 'prm-add-new-menu-group')
     , ('Add Menu Group'                                , 'en', 'prm-add-new-menu-group')
     , ('Añadir Opción a Producto'                      , 'es', 'prm-add-option-to-item')
     , ('Add Option to Item'                            , 'en', 'prm-add-option-to-item')
     , ('Añadir Gasto de Servicios'                     , 'es', 'prm-add-services-expense')
     , ('Add Utilities Expense'                         , 'en', 'prm-add-services-expense')
     , ('Añadir Usuario'                                , 'es', 'prm-add-user')
     , ('Add User'                                      , 'en', 'prm-add-user')
     , ('Añadir Roles'                                  , 'es', 'prm-add-user-roles')
     , ('Add Roles'                                     , 'en', 'prm-add-user-roles')
     , ('Asignar Producto a Persona'                    , 'es', 'prm-assign-bill-item-to-person')
     , ('Assign Item to Person'                         , 'en', 'prm-assign-bill-item-to-person')
     , ('Asignar Permisos a Rol'                        , 'es', 'prm-assign-role-permissions')
     , ('Assign Role Permissions'                       , 'en', 'prm-assign-role-permissions')
     , ('Asignar Roles'                                 , 'es', 'prm-assign-user-roles')
     , ('Assign Roles'                                  , 'en', 'prm-assign-user-roles')
     , ('Traducir'                                      , 'es', 'prm-can-translate')
     , ('Translate'                                     , 'en', 'prm-can-translate')
     , ('Cambiar la Configuración'                      , 'es', 'prm-change-app-values')
     , ('Change the Configuration'                      , 'en', 'prm-change-app-values')
     , ('Cambiar un Producto en la Comanda'             , 'es', 'prm-change-bill-item')
     , ('Change a Bill Item'                            , 'en', 'prm-change-bill-item')
     , ('Cambiar el Precio de un Procucto en la Comanda', 'es', 'prm-change-bill-item-price')
     , ('Change the Price of a Bill Item'               , 'en', 'prm-change-bill-item-price')
     , ('Cambiar la Mesa de la Comanda'                 , 'es', 'prm-change-bill-location')
     , ('Change the Sitting of the Bill'                , 'en', 'prm-change-bill-location')
     , ('Cambiar el Lenguaje de Otros Usuarios'         , 'es', 'prm-change-other-users-language')
     , ('Change Other Users Langauge'                   , 'en', 'prm-change-other-users-language')
     , ('Cambiar el Nombre de Otros Usuarios'           , 'es', 'prm-change-other-users-name')
     , ('Change Other Users Name'                       , 'en', 'prm-change-other-users-name')
     , ('Cambiar la Contraseña de Otros Usuarios'       , 'es', 'prm-change-other-users-password')
     , ('Change Other Users Password'                   , 'en', 'prm-change-other-users-password')
     , ('Cambiar el Inventario'                         , 'es', 'prm-change-stock-status')
     , ('Can Change Stock Status'                       , 'en', 'prm-change-stock-status')
     , ('Cambiar Estado Activo de Otros Usuarios'       , 'es', 'prm-change-user-enabled')
     , ('Change Active State for Other Users'           , 'en', 'prm-change-user-enabled')
     , ('Cobrar Comanda'                                , 'es', 'prm-charge-bill')
     , ('Charge Bill'                                   , 'en', 'prm-charge-bill')
     , ('Hacer Cierre'                                  , 'es', 'prm-close-accounts')
     , ('Close Accounting'                              , 'en', 'prm-close-accounts')
     , ('Añadir Producto a Comanda'                     , 'es', 'prm-create-bill-item')
     , ('Add Bill Item'                                 , 'en', 'prm-create-bill-item')
     , ('Crear Comanda'                                 , 'es', 'prm-create-new-bill')
     , ('Create Bill'                                   , 'en', 'prm-create-new-bill')
     , ('Crear Opción'                                  , 'es', 'prm-create-new-option')
     , ('Create Option'                                 , 'en', 'prm-create-new-option')
     , ('Crear Grupo de Opciones'                       , 'es', 'prm-create-new-option-group')
     , ('Create Option Group'                           , 'en', 'prm-create-new-option-group')
     , ('Borrar Producto en una Comanda'                , 'es', 'prm-delete-bill-item')
     , ('Delete Bill Item'                              , 'en', 'prm-delete-bill-item')
     , ('Borrar Producto'                               , 'es', 'prm-delete-item')
     , ('Delete Item'                                   , 'en', 'prm-delete-item')
     , ('Borrar Roles'                                  , 'es', 'prm-delete-roles')
     , ('Delete Roles'                                  , 'en', 'prm-delete-roles')
     , ('Borrar Usuario'                                , 'es', 'prm-delete-user')
     , ('Delete User'                                   , 'en', 'prm-delete-user')
     , ('Listar Comandas'                               , 'es', 'prm-list-bills')
     , ('List Bills'                                    , 'en', 'prm-list-bills')
     , ('Listar Cuentas Cerradas'                       , 'es', 'prm-list-closed-accounts')
     , ('List Closed Accounts'                          , 'en', 'prm-list-closed-accounts')
     , ('Listar Comandas Carradas'                      , 'es', 'prm-list-closed-bills')
     , ('List Closed Bills'                             , 'en', 'prm-list-closed-bills')
     , ('Listar Servicios Cerrados'                     , 'es', 'prm-list-closed-services')
     , ('List Closed Services'                          , 'en', 'prm-list-closed-services')
     , ('Listar Productos'                              , 'es', 'prm-list-items')
     , ('List Items'                                    , 'en', 'prm-list-items')
     , ('Listar Roles'                                  , 'es', 'prm-list-roles')
     , ('List Roles'                                    , 'en', 'prm-list-roles')
     , ('Listar Servicios'                              , 'es', 'prm-list-services')
     , ('List Services'                                 , 'en', 'prm-list-services')
     , ('Listar Usuarios'                               , 'es', 'prm-list-users')
     , ('List Users'                                    , 'en', 'prm-list-users')
     , ('Imprimir Comanda'                              , 'es', 'prm-print-bill')
     , ('print Bill'                                    , 'en', 'prm-print-bill')
     , ('Remover Opciones de Producto'                  , 'es', 'prm-remove-option-from-item')
     , ('Remove Item Options'                           , 'en', 'prm-remove-option-from-item')
     , ('Asignar Precio del Producto'                   , 'es', 'prm-set-item-charge')
     , ('Set Item Charge'                               , 'en', 'prm-set-item-charge')
     , ('Asignar Grupo de Menú a Producto'              , 'es', 'prm-set-item-menu-group')
     , ('Set Item Menu Group'                           , 'en', 'prm-set-item-menu-group')
     , ('Asignar Nombre de Producto'                    , 'es', 'prm-set-item-name')
     , ('Set Item Name'                                 , 'en', 'prm-set-item-name')
     , ('Asignar Precio de Opción'                      , 'es', 'prm-set-option-charge')
     , ('Set Option Charge'                             , 'en', 'prm-set-option-charge')
     , ('Asignar Grupo de Opción'                       , 'es', 'prm-set-option-group')
     , ('Set Option Group'                              , 'en', 'prm-set-option-group')
     , ('Asignar Estado de Inventario de Opción'        , 'es', 'prm-set-option-in-stock')
     , ('Set Option Stock Status'                       , 'en', 'prm-set-option-in-stock')
     , ('Asignar Nombre de Opción'                      , 'es', 'prm-set-option-name')
     , ('Set Option Name'                               , 'en', 'prm-set-option-name')
     , ('Asignar Opciones a Producto en Comanda'        , 'es', 'prm-set-options-to-bill-item')
     , ('Set Bill Item Options'                         , 'en', 'prm-set-options-to-bill-item')
     , ('Ver Cuentas'                                   , 'es', 'prm-view-accounts')
     , ('View Accounts'                                 , 'en', 'prm-view-accounts')
     , ('Ver Valores de Configuración'                  , 'es', 'prm-view-app-values')
     , ('View App Values'                               , 'en', 'prm-view-app-values')
     , ('Ver Cuenta Cerrada'                            , 'es', 'prm-view-closed-account')
     , ('View Closed Account'                           , 'en', 'prm-view-closed-account')
     , ('Ver Comanda Cerrada'                           , 'es', 'prm-view-closed-bill')
     , ('View Closed Bill'                              , 'en', 'prm-view-closed-bill')
     , ('Ver Servicios Cerrados'                        , 'es', 'prm-view-closed-services')
     , ('View Closed Services'                          , 'en', 'prm-view-closed-services')
     , ('Ver Producto'                                  , 'es', 'prm-view-item')
     , ('View Item'                                     , 'en', 'prm-view-item')
     , ('Ver Registro'                                  , 'es', 'prm-view-log')
     , ('View Log'                                      , 'en', 'prm-view-log')
     , ('Ver Comanda Abierta'                           , 'es', 'prm-view-open-bill')
     , ('View Open Bill'                                , 'en', 'prm-view-open-bill')
     , ('Ver Opción'                                    , 'es', 'prm-view-option')
     , ('View Option'                                   , 'en', 'prm-view-option')
     , ('Ver Otros Usuarios'                            , 'es', 'prm-view-other-users')
     , ('View Other Users'                              , 'en', 'prm-view-other-users')
     , ('Ver Rol'                                       , 'es', 'prm-view-role')
     , ('View Role'                                     , 'en', 'prm-view-role')
;
